name: Auto Pull Request from Trello

on:
  repository_dispatch:
    types: [trello-pr]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Criar Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "PR automático gerado pelo Trello"
          title: "Revisão: Atualização de Feature 🚀"
          body: "Este Pull Request foi gerado automaticamente ao mover uma tarefa para 'Revisão' no Trello."
          base: main
          branch: feature-auto-pr
